exclude:
  - node_modules
  - script

sass:
  style: :compressed


github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/hyperhamster535.github.io"
  
gems:
  - jekyll-octicons
  
title: Proximas
description: The official site of Proximas.
