
# Build settings
markdown: kramdown
theme: jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
header_pages:
  - index.md
  - projects.md
  - about.md
  

style: dark # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)
footer: '
find me on 
<ul>
<li><a href="https://twitter.com/Pr0x1mas">twitter</a></li>
<li><a href="https://github.com/Pr0x1mas">github</a></li>
<li><a href="https://www.youtube.com/channel/UCs6xm-dG9-NVL9UDl_kdGHQ">youtube</a></li>
</ul>
'

